# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-22 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Bookeeper', 'Bookeeper'), ('Cashier', 'Cashier')], default='Admin', max_length=10),
        ),
    ]
