# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-28 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20161022_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='position',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Bookkeeper', 'Bookkeeper'), ('Cashier', 'Cashier')], default='Admin', max_length=10),
        ),
    ]
