# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-06 04:20
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cust_number', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Joined Date: ')),
                ('firstname', models.CharField(default='', max_length=99)),
                ('middlename', models.CharField(default='', max_length=99)),
                ('lastname', models.CharField(default='', max_length=99)),
                ('age', models.PositiveIntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)])),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('address', models.CharField(default='Davao City', max_length=99)),
                ('birthdate', models.DateField(blank=True)),
                ('educ_attain', models.CharField(choices=[('Grade School', 'Grade School'), ('High School', 'High School'), ('College Graduate', 'College Graduate'), ('College Undergraduate', 'College Undergraduate')], default='College Graduate', max_length=22)),
                ('occupation', models.CharField(default='', max_length=99)),
                ('membership_type', models.CharField(choices=[('Driver', 'Driver'), ('Operator', 'Operator'), ('Allied Worker', 'Allied Worker')], max_length=13)),
                ('client_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=9)),
                ('client_id_type', models.CharField(choices=[('SSS', 'SSS'), ('TIN', 'TIN'), ('Others', 'Others')], max_length=7)),
                ('client_id_number', models.CharField(default='', max_length=20)),
                ('beneficiary', models.CharField(choices=[('Single', 'Single'), ('Spouse', 'Spouse'), ('Parents', 'Parents'), ('Heirs', 'Heirs')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='client_capital',
            fields=[
                ('cap_id', models.AutoField(primary_key=True, serialize=False)),
                ('cap_contrib_date', models.DateField(default=datetime.datetime.now, verbose_name='Date of Contribution: ')),
                ('cap_contrib', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('capital', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cap_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('val', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_loan', models.CharField(choices=[('Providential', 'Providential'), ('Emergency', 'Emergency')], max_length=12)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('loan_overflow', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('interest_rate_over', models.DecimalField(blank=True, decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('loan_duration', models.PositiveIntegerField()),
                ('loan_status', models.CharField(choices=[('Outstanding', 'Outstanding'), ('Paid', 'Paid'), ('Restructured', 'Restructured')], default='Outstanding', max_length=12)),
                ('update', models.BooleanField(default=False)),
                ('overdue', models.BooleanField(default=False)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('collateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Collateral')),
            ],
        ),
        migrations.CreateModel(
            name='loanApplication',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateField(default=datetime.datetime.now, verbose_name='Date of application')),
                ('app_status', models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Approved', 'Approved'), ('Paid', 'Paid')], default='Pending', max_length=15)),
                ('app_kind', models.CharField(choices=[('Providential Loan', 'Providential Loan'), ('Emergency Loan', 'Emergency Loan')], default='Providential Loan', max_length=20)),
                ('app_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('restruct', models.BooleanField(default=False)),
                ('app_comaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comaker', to='clients.Client')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='MAF',
            fields=[
                ('maf_id', models.AutoField(primary_key=True, serialize=False)),
                ('maf_contrib_date', models.DateField(default=datetime.datetime.now, verbose_name='Date of Contribution: ')),
                ('maf_ref', models.CharField(default='forwarded balance', max_length=99)),
                ('maf_debit', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('maf_credit', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('maf_total', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True)),
                ('maf_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ODF',
            fields=[
                ('odf_id', models.AutoField(primary_key=True, serialize=False)),
                ('odf_contrib_date', models.DateField(default=datetime.datetime.now, verbose_name='Date of Contribution: ')),
                ('odf_ref', models.CharField(default='forwarded balance', max_length=99)),
                ('odf_debit', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('odf_credit', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('odf_total', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True)),
                ('odf_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.CreateModel(
            name='payLoanLedger_in',
            fields=[
                ('trans_date', models.DateField(default=datetime.datetime.now)),
                ('reference', models.CharField(default='-', max_length=20, null=True)),
                ('debit_loanGranted', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('credit_payment', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('int_per_month', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_loan_recievable', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True)),
                ('loan_pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_pay_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Check')], default='Cash', max_length=7)),
                ('loan_pay_received_by', models.CharField(default='Cashier', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='payLoanLedger_over',
            fields=[
                ('trans_date', models.DateField(default=datetime.datetime.now)),
                ('reference', models.CharField(default='-', max_length=20, null=True)),
                ('debit_loanGranted', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('credit_payment', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('int_per_month', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_loan_recievable', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True)),
                ('loan_pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_pay_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Check')], default='Cash', max_length=7)),
                ('loan_pay_received_by', models.CharField(default='Cashier', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='Restruct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_in_interest', models.DecimalField(blank=True, decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('loan_in_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('loan_over_interest', models.DecimalField(blank=True, decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('loan_over_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('restruct_fee', models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('approval_status', models.BooleanField(default=True)),
                ('restruct_status', models.CharField(choices=[('Outstanding', 'Outstanding'), ('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=11)),
                ('loan_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_root', to='clients.loanApplication')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('savings_id', models.AutoField(primary_key=True, serialize=False)),
                ('savings_contrib_date', models.DateField(default=datetime.datetime.now, verbose_name='Date of Contribution: ')),
                ('savings_ref', models.CharField(default='forwarded balance', max_length=99)),
                ('savings_debit', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('savings_credit', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('savings_total', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True)),
                ('savings_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.loanApplication'),
        ),
    ]
