# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-30 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cust_number', models.AutoField(primary_key=True, serialize=False)),
                ('join_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Joined Date: ')),
                ('firstname', models.CharField(default='', max_length=99)),
                ('middlename', models.CharField(default='', max_length=99)),
                ('lastname', models.CharField(default='', max_length=99)),
                ('age', models.IntegerField(default=18)),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], default='Single', max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=11)),
                ('address', models.CharField(default='Davao City', max_length=99)),
                ('birthdate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('educ_attain', models.CharField(choices=[('Grade School', 'Grade School'), ('High School', 'High School'), ('College Graduate', 'College Graduate'), ('College Undergraduate', 'College Undergraduate')], default='College Graduate', max_length=22)),
                ('occupation', models.CharField(default='', max_length=99)),
                ('membership_type', models.CharField(choices=[('Driver', 'Driver'), ('Operator', 'Operator'), ('Allied Worker', 'Allied Worker')], default='Allied Worker', max_length=13)),
                ('client_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=9)),
                ('capital', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('client_id_type', models.CharField(choices=[('SSS', 'SSS'), ('TIN', 'TIN'), ('Others', 'Others')], default='SSS', max_length=7)),
                ('client_id_number', models.CharField(default='', max_length=20)),
                ('client_odf', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('client_maf', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('beneficiary', models.CharField(choices=[('Single', 'Single'), ('Wife', 'Wife'), ('Parents', 'Parents')], default='Single', max_length=8)),
            ],
        ),
    ]
