# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-05 10:50
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('savings_id', models.AutoField(primary_key=True, serialize=False)),
                ('savings_contrib_date', models.DateField(default=datetime.datetime.now, verbose_name='Date of Contribution: ')),
                ('savings_ref', models.CharField(default='forwarded balance', max_length=99)),
                ('savings_debit', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('savings_credit', models.DecimalField(blank=True, decimal_places=2, default='-', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('savings_total', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=10, null=True)),
                ('savings_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
