# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-24 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restruct',
            name='approval_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='restruct',
            name='restruct_status',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=11),
        ),
    ]
