# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-18 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170818_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='beneficiary',
            field=models.CharField(choices=[('Single', 'Single'), ('Wife', 'Spouse'), ('Parents', 'Parents'), ('Heirs', 'Heirs')], max_length=8),
        ),
    ]
