# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-04 20:27
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20161031_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanApplication',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date of application: ')),
                ('app_status', models.CharField(choices=[('Waiting', 'Waiting'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Waiting', max_length=15)),
                ('app_kind', models.CharField(choices=[('Providential Loan', 'Providential Loan'), ('Emergency Loan', 'Emergency Loan')], default='Providential Loan', max_length=20)),
                ('app_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('app_approval', models.DateField(blank=True, null=True)),
                ('app_comaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comaker', to='clients.Client')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
