# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-24 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20170818_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_overflow',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
    ]
