# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_loanapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='app_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date of application: '),
        ),
    ]
