# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 12:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20161123_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='app_approval',
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='app_amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='app_comaker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comaker', to='clients.Client'),
        ),
    ]
