# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-31 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20170830_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
    ]
