# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20161123_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='app_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Pending', max_length=15),
        ),
    ]
