# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-31 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20170831_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Paid', 'Paid')], default='Outstanding', max_length=11),
        ),
    ]
