# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20161123_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='loanApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_status', models.CharField(choices=[('Pending', 'Pending'), ('Denied', 'Denied'), ('Approved', 'Approved')], default='Pending', max_length=15)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
