# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_loanapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapproval',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.loanApplication'),
        ),
    ]
