# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-04 16:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_restruct'),
    ]

    operations = [
        migrations.AddField(
            model_name='restruct',
            name='restruct_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='restruct',
            name='restruct_status',
            field=models.BooleanField(default=False),
        ),
    ]
