# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-23 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20161123_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='app_comaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comaker', to='clients.Client'),
        ),
    ]
