# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-04 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20161123_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapproval',
            name='client',
        ),
        migrations.DeleteModel(
            name='loanApproval',
        ),
    ]
