# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20170905_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Paid', 'Paid'), ('Restructured', 'Restructured')], default='Outstanding', max_length=11),
        ),
    ]
