# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20170905_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restruct',
            name='loan_root',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_root', to='clients.loanApplication'),
        ),
    ]
