# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-04 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20161204_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
