# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-04 09:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_loanapplication_approval_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_loan', models.CharField(choices=[('Providential', 'Providential'), ('Emergency', 'Emergency')], max_length=12)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('loan_duration', models.PositiveIntegerField()),
                ('loan_status', models.CharField(choices=[('Outstanding', 'Outstanding'), ('Paid', 'Paid')], max_length=11)),
                ('check_number', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('collateral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Collateral')),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clients.loanApplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_information',
            field=models.ManyToManyField(to='clients.LoanInformation'),
        ),
    ]
