# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-09 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20170909_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restruct',
            old_name='restruct_status',
            new_name='approval_status',
        ),
    ]
