# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20170909_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='restruct',
            name='restruct_status',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Paid', 'Paid')], default='Outstanding', max_length=11),
        ),
    ]
