# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_auto_20161204_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='check_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('Outstanding', 'Outstanding'), ('Paid', 'Paid')], default='Outstanding', max_length=11),
        ),
    ]
