# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-08 13:28
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20161204_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='payLoan',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('pay_trans_date', models.DateField(default=datetime.datetime.now)),
                ('pay_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=7)),
                ('pay_for', models.CharField(choices=[('Loan', 'Loan'), ('MAF', 'MAF'), ('ODF', 'ODF')], default='Loan', max_length=5)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
