# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_restruct_restruct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='restruct',
            field=models.BooleanField(default=False),
        ),
    ]
